name: CI
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4
      - name: publishToMavenLocal for functionalTest
        run: ./gradlew publishToMavenLocal
      - name: Check
        run: ./gradlew check detektMain detektTest detektFunctionalTest
